FROM golang:1.24

WORKDIR /app

# Install Air
RUN go install github.com/cosmtrek/air@v1.16.1

COPY . .

# Install dependencies
RUN go mod download

EXPOSE 5749

# Run air
CMD ["air", "-c", ".air.toml"]
