name: social-api
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: cosmtrek/air
        working_dir: /app
        ports:
            - "5749:5749"
        volumes:
            - .:/app # Mount entire directory for hot reload
        environment:
            - PORT=5749
            - DATABASE_URL=postgres://admin:adminpassword@db:5432/tickit?sslmode=disable
            - DATABASE_MAX_OPEN_CONNS=30
            - DATABASE_MAX_IDLE_CONNS=30
            - DATABASE_MAX_IDLE_TIME=15m
        networks:
            - backend
        depends_on:
            - db
            - redis

    db:
        image: postgres:17.0-alpine
        container_name: postgres-db
        environment:
            POSTGRES_DB: tickit
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: adminpassword
        networks:
            - backend
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./scripts/init:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"

    redis:
        image: redis:8.0-M02-alpine
        restart: unless-stopped
        container_name: redis
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning
        networks:
            - backend

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOST=redis
        ports:
            - "127.0.0.1:8081:8081"
        depends_on:
            - redis
        restart: unless-stopped

volumes:
    db-data:

networks:
    backend:
        driver: bridge
