// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Issue struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	Title       string
	Description pgtype.Text
	Status      pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Project struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Task struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	AssigneeID  pgtype.UUID
	Title       string
	Description pgtype.Text
	Status      pgtype.Text
	Priority    pgtype.Text
	DueDate     pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Team struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type TeamMember struct {
	TeamID    pgtype.UUID
	UserID    pgtype.UUID
	Role      pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
